---
- name: PASSWORD POLICY 
  hosts: win
  gather_facts: yes

  tasks:

     - name: Set Minimum password age to 1 or more days | cis minimum-password-age 1.1.3
       win_command: net accounts /minpwage:1
       register: minPassAge
       args:
         creates: C:\minPassAge.lock

     - name: Create minPassAge.lock if password history is enforced
       win_copy:
         dest: C:\minPassAge.lock
         content: ""
         force: no
       when: minPassAge
