---
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Enable Strong Encryption for Windows Network Sessions on Servers | windows-base-203
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0
          name: "NtlmMinServerSec"
          data: "537395200"
          type: dword
