---
- name: PASSWORD POLICY 
  hosts: win
  gather_facts: yes

  tasks:
     - name: Set Enforce password history to 24 or more passwords | cis enforce-password-history 1.1.1
       win_command: net accounts /uniquepw:24
       register: passHistory
       args:
         creates: C:\passHistory.lock

     - name: Create passHistory.lock if password history is enforced
       win_copy:
         dest: C:\passHistory.lock
         content: ""
         force: no
       when: passHistory

