---
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Safe DLL Search Mode is Enabled | windows-base-101
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Control\Session Manager
          name: "SafeDllSearchMode"
          data: "0"
          type: dword
