---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
  
    - name: "9.1.5 (L1) Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
              name: "LogFilePath"
              data: "%systemroot%\\System32\\logfiles\\firewall\\domainfw.log"
              type: string  
