---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:

    - name: "9.1.8 (L1) Ensure 'Windows Firewall: Private: Logging: Log successful connections' is set to 'Yes'"
      win_regedit:
              path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
              name: "LogSuccessfulConnections"
              data: "1"
              type: dword 
