---
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Disable SMB1 to Windows Shares | windows-base-105
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
          name: "SMB1"
          data: "0"
          type: dword
