---
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Force Encrypted Windows Network Passwords | windows-base-104
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters
          name: "EnablePlainTextPassword"
          data: "0"
          type: dword

