---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:

     - name: Configure System Event Log (Security) | windows-audit-101
       win_regedit:
         path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security
         name: "MaxSize"
         data: "1"
         type: dword

