---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
  
    - name: "9.1.1 (L1) Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
              name: "EnableFirewall"
              data: "1"
              type: dword
