---
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Strong Windows NTLMv2 Authentication Enabled; Weak LM Disabled | windows-base-201
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Control\Lsa
          name: "LmCompatibilityLevel"
          data: "4"
          type: dword
