---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
  
    - name: "9.1.5 (L1) Ensure 'Windows Firewall: Private: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
              name: "LogFilePath"
              data: "%systemroot%\\System32\\logfiles\\firewall\\privatefw.log"
              type: string  

