---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
  
    - name: "9.1.2 (L1) Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
              name: "DefaultInboundAction"
              data: "1"
              type: dword 
