---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
    - name: "9.1.7 (L1) Ensure 'Windows Firewall: Private: Logging: Log dropped packets' is set to 'Yes'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
              name: "LogDroppedPackets"
              data: "1"
              type: dword
