---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:

     - name: Configure System Event Log (Setup) | windows-audit-102
       win_regedit:
         path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup
         name: "MaxSize"
         data: "1"
         type: dword
