---
- name: PASSWORD POLICY
  hosts: win
  gather_facts: yes

  tasks:
          
    - name: "9.1.3 (L1) Ensure 'Windows Firewall: Private: Outbound connections' is set to 'Allow (default)'"
      win_regedit:
              path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
              name: "DefaultOutboundAction"
              data: "0"
              type: dword  
