--
- name: USER RIGHTS
  hosts: win
  gather_facts: yes

  tasks:

     - name: Enable Strong Encryption for Windows Network Sessions on Clients | windows-base-202
       win_regedit:
          path: HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0
          name: "NtlmMinClientSec"
          data: "537395200"
          type: dword
